JoaoAfonsoWeb/Models/ErrorViewModel.cs
namespace JoaoAfonsoWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JoaoAfonsoWeb/Controllers/AnimacaoController.cs
using JoaoAfonso.Domain.Entities;
using JoaoAfonso.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;

namespace JoaoAfonsoWeb.Controllers
{
    public class AnimacaoController : Controller
    {

        private readonly ApplicationDbContext _db;

        public AnimacaoController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var animacao = _db.Animacao_Trabalhos.ToList();
            return View(animacao);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Animacao_trabalhos obj)
        {
            if (obj.Nome == obj.Descricao)
            {
                ModelState.AddModelError("", "The Description cannot match the Name.");
            }
            if (ModelState.IsValid)
            {
                _db.Animacao_Trabalhos.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

    }
}

JoaoAfonsoWeb/Controllers/EsculturaController.cs
using Microsoft.AspNetCore.Mvc;

namespace JoaoAfonsoWeb.Controllers
{
    public class EsculturaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

JoaoAfonsoWeb/Controllers/HomeController.cs
using JoaoAfonsoWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace JoaoAfonsoWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Modelacao()
        {
            return View();
        }

        public IActionResult Animacao()
        {
            return View();
        }

        public IActionResult Escultura()
        {
            return View();
        }

        public IActionResult Contactos()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JoaoAfonsoWeb/Controllers/ModelacaoController.cs
using Microsoft.AspNetCore.Mvc;

namespace JoaoAfonsoWeb.Controllers
{
    public class ModelacaoController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }
    }
}

JoaoAfonsoWeb/Views/Animacao/Create.cshtml
@model JoaoAfonso.Domain.Entities.Animacao_trabalhos

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-gray m-lg-3 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-3">Trabalhos Animação</h2>
            </div>
        </div>
    </div>
    <div class="card-body border-bottom p-4">
        <form method="post" class="row">
            <div class="p-3">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Nome" class="form-control border shadow" />
                    <label asp-for="Nome" class="ms-2"></label>
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Descricao" class="form-control border shadow" />
                    <label asp-for="Descricao" class="ms-2"></label>
                    <span asp-validation-for="Descricao" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.SoftwareUsado" class="form-control border shadow" />
                    <label asp-for="SoftwareUsado" class="ms-2"></label>
                    <span asp-validation-for="SoftwareUsado" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Duracao" class="form-control border shadow" />
                    <label asp-for="Duracao" class="ms-2"></label>
                    <span asp-validation-for="Duracao" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.UrlImagem" class="form-control border shadow" />
                    <label asp-for="UrlImagem" class="ms-2"></label>
                    <span asp-validation-for="UrlImagem" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.TamanhoFicheiro" class="form-control border shadow" />
                    <label asp-for="TamanhoFicheiro" class="ms-2"></label>
                    <span asp-validation-for="TamanhoFicheiro" class="text-danger"></span>
                </div>

                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Criar
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Animacao" asp-action="Index" class="btn btn-secondary w-100">
                            <i class=" bi bi-x-circle"></i>Cancelar
                        </a>
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

JoaoAfonsoWeb/Views/Animacao/Index.cshtml
@model IEnumerable<JoaoAfonso.Domain.Entities.Animacao_trabalhos>


<div class="w-100 card border-0 p-4">
    <div class="card-header bg-gray m-lg-3 py-3">
        <div class="card custom-white-card">
            <div class="row">
                <div class="col-12 text-center">
                    <h2 class="text-white py-3">Trabalhos Animação</h2>
                </div>
            </div>
        </div>
    </div>

    <div class="card-body border-bottom p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Animacao" asp-action="Create" class="btn btn-outline-white">
                    <i class="bi bi-plus-square-fill"></i> Criar nova entrada de Animação
                </a>
            </div>
        </div>


        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Descricao</th>
                    <th>SoftwareUsado</th>
                    <th>Duracao</th>
                    <th>UrlImagem</th>
                    <th>TamanhoFicheiro</th>
                    <th></th>
                </tr>

            </thead>

            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Nome</td>
                        <td>@obj.Descricao</td>
                        <td>@obj.SoftwareUsado</td>
                        <td>@obj.Duracao</td>
                        <td>@obj.UrlImagem</td>
                        <td>@obj.TamanhoFicheiro</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Animacao" asp-action="Update" asp-route-animacaoID="@obj.ID class="btn btn-sucess mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>

                                <a asp-controller="Animacao" asp-action="Delete" asp-route-animacaoID="@obj.ID class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>

                        </td>
                    </tr>
                }
            </tbody>


        </table>

    </div>
</div>

JoaoAfonsoWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

JoaoAfonsoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark"> 
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JoaoAfonsoWeb</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" integrity="sha512-b2QcS5SsA8tZodcDtGRELiGv5SaKSk1vDHDaQRda0htPYWZ6046lr3kJ5bAAQdpV2mmA/4v0wQF9MyU6/pDIAg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JoaoAfonsoWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JoaoAfonsoWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Modelacao">Modelação</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Animacao" asp-action="Index">Animação</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Escultura">Escultura</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contactos">Contactos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Política de privacidade</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - JoaoAfonsoWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.min.js" integrity="sha512-WW8/jxkELe2CAiE4LvQfwm1rajOS8PHasCCx+knHG0gBHt8EXxS6T6tJRTGuDQVnluuAvMxWF4j8SNFDKceLFg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>